Metrics/AbcSize:
  Max: 43

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 31

Metrics/PerceivedComplexity:
  Max: 15

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false
