source 'https://rubygems.org'

gem 'byebug'
gem 'dotenv'
gem 'httparty'
gem 'i2c'
gem 'rpi_gpio', github: 'https://github.com/ClockVapor/rpi_gpio.git' if ENV['RPI'] == '1'
gem 'sinatra'
gem 'spi'
gem 'uart'
